version: 0.0
os: linux
files:
  - source: scripts.zip
    destination: /home/ec2-user/app/Scripts
  - source: unzip.sh
    destination: /home/ec2-user/app/Scripts
permissions:
    - object: /home/ec2-user/app/Scripts
      pattern: "*.*"
      owner: ec2-user
      group: ec2-user
      mode: 755
      type:
        - file
hooks:
  AfterInstall:
    - location: unzip.sh
      timeout: 300
      runas: ec2-user
