version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Or your desired Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt	
      - echo "Dos2unix ..."
      - dos2unix *.*
  build:
    commands:
      - echo "Creating zip archive..."
      - zip scripts.zip *.py
  post_build:
    commands:
      - echo "Build completed."
      
artifacts:
  files:
    - scripts.zip
    - unzip.sh
    - appspec.yml
    - change_permission.sh


