version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Or your desired Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt	
  build:
    commands:
      - echo "Creating /app directory..."
      - mkdir app
      - echo "Creating zip archive..."
      - zip app/ATS_gemini.zip ATS_gemini.py
      - echo "Copying script to /app directory..."
      - cp ATS_gemini.py app/
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - app/**/*
  discard-paths: no

