version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Or your desired Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt	
  build:
    commands:
      - echo "copy unzip.sh file..."
      - cp unzip.sh unzip.sh
      - echo "Creating zip archive..."
      - zip scripts.zip *.py
  post_build:
    commands:
      - echo "Build completed."
      
artifacts:
  files:
    - scripts.zip

